INSERT INTO mechanics (mechanic_id, mechanic_name) VALUES
    (1,'Taunt'),
    (2,'Windfury'),
    (3,'Poisonous'),
    (4,'Charge'),
    (5,'Combo'),
    (6,'Discover'),
    (7,'Battlecry'),
    (8,'AffectedBySpellPower'),
    (9,'Jade Golem'),
    (10,'Secret'),
    (11,'Deathrattle'),
    (12,'Silence'),
    (13,'InvisibleDeathrattle'),
    (14,'Overload'),
    (15,'Stealth'),
    (16,'Enrage'),
    (17,'ImmuneToSpellpower'),
    (18,'Aura'),
    (19,'Divine Shield'),
    (20,'AdjacentBuff'),
    (21,'Freeze'),
    (22,'Spell Damage'),
    (23,'Inspire');
